services:
    _defaults:
        autowire: true
        autoconfigure: true

    MenAtWork\ManipulateTemplates\:
        resource: ../src
        exclude: ../src/{ContaoManager,DependencyInjection,ManipulateTemplatesBundle.php}
